/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.tigrisdata.tigris_core.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.tigrisdata.tigris_core.utils.SpeakeasyMetadata;

public class CacheDelRequest {
    @SpeakeasyMetadata("request:mediaType=application/json")
    public java.util.Map<String, Object> requestBody;
    public CacheDelRequest withRequestBody(java.util.Map<String, Object> requestBody) {
        this.requestBody = requestBody;
        return this;
    }
    
    /**
     * cache key
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=key")
    public String key;
    public CacheDelRequest withKey(String key) {
        this.key = key;
        return this;
    }
    
    /**
     * cache name
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=name")
    public String name;
    public CacheDelRequest withName(String name) {
        this.name = name;
        return this;
    }
    
    /**
     * Tigris project name
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=project")
    public String project;
    public CacheDelRequest withProject(String project) {
        this.project = project;
        return this;
    }
    
    public CacheDelRequest(@JsonProperty("RequestBody") java.util.Map<String, Object> requestBody, @JsonProperty("key") String key, @JsonProperty("name") String name, @JsonProperty("project") String project) {
        this.requestBody = requestBody;
        this.key = key;
        this.name = name;
        this.project = project;
  }
}
