/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.tigrisdata.tigris_core.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.tigrisdata.tigris_core.utils.SpeakeasyMetadata;

public class CacheCreateCacheRequest {
    @SpeakeasyMetadata("request:mediaType=application/json")
    public com.tigrisdata.tigris_core.models.shared.CreateCacheRequest createCacheRequest;
    public CacheCreateCacheRequest withCreateCacheRequest(com.tigrisdata.tigris_core.models.shared.CreateCacheRequest createCacheRequest) {
        this.createCacheRequest = createCacheRequest;
        return this;
    }
    
    /**
     * cache name
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=name")
    public String name;
    public CacheCreateCacheRequest withName(String name) {
        this.name = name;
        return this;
    }
    
    /**
     * Tigris project name
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=project")
    public String project;
    public CacheCreateCacheRequest withProject(String project) {
        this.project = project;
        return this;
    }
    
    public CacheCreateCacheRequest(@JsonProperty("CreateCacheRequest") com.tigrisdata.tigris_core.models.shared.CreateCacheRequest createCacheRequest, @JsonProperty("name") String name, @JsonProperty("project") String project) {
        this.createCacheRequest = createCacheRequest;
        this.name = name;
        this.project = project;
  }
}
