/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.tigrisdata.tigris_core.models.operations;

import com.tigrisdata.tigris_core.utils.SpeakeasyMetadata;

public class CacheGetSetPathParams {
    /**
     * cache key
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=key")public String key;
    public CacheGetSetPathParams withKey(String key) {
        this.key = key;
        return this;
    }
    
    /**
     * cache name
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=name")public String name;
    public CacheGetSetPathParams withName(String name) {
        this.name = name;
        return this;
    }
    
    /**
     * Tigris project name
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=project")public String project;
    public CacheGetSetPathParams withProject(String project) {
        this.project = project;
        return this;
    }
    
}
