/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.tigrisdata.tigris_core.models.operations;



public class RealtimePresenceRequest {
    public RealtimePresencePathParams pathParams;
    public RealtimePresenceRequest withPathParams(RealtimePresencePathParams pathParams) {
        this.pathParams = pathParams;
        return this;
    }
    
}
