/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.tigrisdata.tigris_core.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.tigrisdata.tigris_core.utils.SpeakeasyMetadata;

public class SearchCreateOrUpdateIndexRequest {
    @SpeakeasyMetadata("request:mediaType=application/json")
    public com.tigrisdata.tigris_core.models.shared.CreateOrUpdateIndexRequest createOrUpdateIndexRequest;
    public SearchCreateOrUpdateIndexRequest withCreateOrUpdateIndexRequest(com.tigrisdata.tigris_core.models.shared.CreateOrUpdateIndexRequest createOrUpdateIndexRequest) {
        this.createOrUpdateIndexRequest = createOrUpdateIndexRequest;
        return this;
    }
    
    /**
     * search index name.
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=name")
    public String name;
    public SearchCreateOrUpdateIndexRequest withName(String name) {
        this.name = name;
        return this;
    }
    
    /**
     * Tigris project name.
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=project")
    public String project;
    public SearchCreateOrUpdateIndexRequest withProject(String project) {
        this.project = project;
        return this;
    }
    
    public SearchCreateOrUpdateIndexRequest(@JsonProperty("CreateOrUpdateIndexRequest") com.tigrisdata.tigris_core.models.shared.CreateOrUpdateIndexRequest createOrUpdateIndexRequest, @JsonProperty("name") String name, @JsonProperty("project") String project) {
        this.createOrUpdateIndexRequest = createOrUpdateIndexRequest;
        this.name = name;
        this.project = project;
  }
}
