/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.tigrisdata.tigris_core.models.operations;

import com.tigrisdata.tigris_core.utils.SpeakeasyMetadata;

public class SearchCreateOrReplacePathParams {
    /**
     * index name where to create documents.
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=index")public String index;
    public SearchCreateOrReplacePathParams withIndex(String index) {
        this.index = index;
        return this;
    }
    
    /**
     * Project name whose db is under target to insert documents.
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=project")public String project;
    public SearchCreateOrReplacePathParams withProject(String project) {
        this.project = project;
        return this;
    }
    
}
