/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.tigrisdata.tigris_core.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.tigrisdata.tigris_core.utils.SpeakeasyMetadata;

public class TigrisDescribeDatabaseRequest {
    @SpeakeasyMetadata("request:mediaType=application/json")
    public com.tigrisdata.tigris_core.models.shared.DescribeDatabaseRequest describeDatabaseRequest;

    public TigrisDescribeDatabaseRequest withDescribeDatabaseRequest(com.tigrisdata.tigris_core.models.shared.DescribeDatabaseRequest describeDatabaseRequest) {
        this.describeDatabaseRequest = describeDatabaseRequest;
        return this;
    }
    
    /**
     * Project name whose db is under target to get description.
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=project")
    public String project;

    public TigrisDescribeDatabaseRequest withProject(String project) {
        this.project = project;
        return this;
    }
    
    public TigrisDescribeDatabaseRequest(@JsonProperty("DescribeDatabaseRequest") com.tigrisdata.tigris_core.models.shared.DescribeDatabaseRequest describeDatabaseRequest, @JsonProperty("project") String project) {
        this.describeDatabaseRequest = describeDatabaseRequest;
        this.project = project;
  }
}
