/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.tigrisdata.tigris_core.models.operations;

import com.tigrisdata.tigris_core.utils.SpeakeasyMetadata;

public class TigrisCommitTransactionRequest {
    @SpeakeasyMetadata("request:mediaType=application/json")
    public com.tigrisdata.tigris_core.models.shared.CommitTransactionRequest commitTransactionRequest;
    public TigrisCommitTransactionRequest withCommitTransactionRequest(com.tigrisdata.tigris_core.models.shared.CommitTransactionRequest commitTransactionRequest) {
        this.commitTransactionRequest = commitTransactionRequest;
        return this;
    }
    
    /**
     * Project name whose DB this transaction belongs to.
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=project")
    public String project;
    public TigrisCommitTransactionRequest withProject(String project) {
        this.project = project;
        return this;
    }
    
}
