/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.tigrisdata.tigris_core.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.tigrisdata.tigris_core.utils.SpeakeasyMetadata;

public class TigrisDeleteAppKeyRequest {
    @SpeakeasyMetadata("request:mediaType=application/json")
    public com.tigrisdata.tigris_core.models.shared.DeleteAppKeyRequest deleteAppKeyRequest;
    public TigrisDeleteAppKeyRequest withDeleteAppKeyRequest(com.tigrisdata.tigris_core.models.shared.DeleteAppKeyRequest deleteAppKeyRequest) {
        this.deleteAppKeyRequest = deleteAppKeyRequest;
        return this;
    }
    
    /**
     * project name
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=project")
    public String project;
    public TigrisDeleteAppKeyRequest withProject(String project) {
        this.project = project;
        return this;
    }
    
    public TigrisDeleteAppKeyRequest(@JsonProperty("DeleteAppKeyRequest") com.tigrisdata.tigris_core.models.shared.DeleteAppKeyRequest deleteAppKeyRequest, @JsonProperty("project") String project) {
        this.deleteAppKeyRequest = deleteAppKeyRequest;
        this.project = project;
  }
}
