/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.tigrisdata.tigris_core.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.tigrisdata.tigris_core.utils.SpeakeasyMetadata;

public class TigrisSearchRequest {
    @SpeakeasyMetadata("request:mediaType=application/json")
    public com.tigrisdata.tigris_core.models.shared.SearchRequest searchRequest;
    public TigrisSearchRequest withSearchRequest(com.tigrisdata.tigris_core.models.shared.SearchRequest searchRequest) {
        this.searchRequest = searchRequest;
        return this;
    }
    
    /**
     * Collection name to search documents from.
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=collection")
    public String collection;
    public TigrisSearchRequest withCollection(String collection) {
        this.collection = collection;
        return this;
    }
    
    /**
     * Project name whose db is under target to search documents from.
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=project")
    public String project;
    public TigrisSearchRequest withProject(String project) {
        this.project = project;
        return this;
    }
    

    public TigrisSearchRequest(@JsonProperty("SearchRequest") com.tigrisdata.tigris_core.models.shared.SearchRequest searchRequest, @JsonProperty("collection") String collection, @JsonProperty("project") String project) {
    this.searchRequest = searchRequest;
this.collection = collection;
this.project = project;
  }
}
