/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.tigrisdata.tigris_core.models.operations;

import com.tigrisdata.tigris_core.utils.SpeakeasyMetadata;

public class TigrisImportPathParams {
    /**
     * Collection name where to import documents.
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=collection")public String collection;
    public TigrisImportPathParams withCollection(String collection) {
        this.collection = collection;
        return this;
    }
    
    /**
     * Project name whose db is under target to import documents.
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=project")public String project;
    public TigrisImportPathParams withProject(String project) {
        this.project = project;
        return this;
    }
    
}
