/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.tigrisdata.tigris_core.models.operations;

import com.tigrisdata.tigris_core.utils.SpeakeasyMetadata;

public class TigrisDeleteBranchPathParams {
    /**
     * Name of the database branch to delete. <p></p>**Note**: `main` branch cannot be deleted, use DeleteProject instead
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=branch")public String branch;
    public TigrisDeleteBranchPathParams withBranch(String branch) {
        this.branch = branch;
        return this;
    }
    
    /**
     * Delete a database branch in this project
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=project")public String project;
    public TigrisDeleteBranchPathParams withProject(String project) {
        this.project = project;
        return this;
    }
    
}
