/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.tigrisdata.tigris_core.models.operations;



public class TigrisListAppKeysRequest {
    public TigrisListAppKeysPathParams pathParams;
    public TigrisListAppKeysRequest withPathParams(TigrisListAppKeysPathParams pathParams) {
        this.pathParams = pathParams;
        return this;
    }
    
}
