/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.tigrisdata.tigris_core.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * AdditionalFunction - Additional function to apply on metrics query
 */
public class AdditionalFunction {
    /**
     * Rollup function aggregates the slices of metrics returned by original query and lets you operate on the slices using aggregator and constructs the bigger slice of your choice of interval (specified in seconds).
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("rollup")
    public RollupFunction rollup;
    public AdditionalFunction withRollup(RollupFunction rollup) {
        this.rollup = rollup;
        return this;
    }
    
    public AdditionalFunction(){}
}
