/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.tigrisdata.tigris_core.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

public class CreateByIdRequest {
    /**
     * A JSON document that needs to be indexed.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("document")
    public String document;
    public CreateByIdRequest withDocument(String document) {
        this.document = document;
        return this;
    }
    
    /**
     * document id.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("id")
    public String id;
    public CreateByIdRequest withId(String id) {
        this.id = id;
        return this;
    }
    
    /**
     * index name where to create document.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("index")
    public String index;
    public CreateByIdRequest withIndex(String index) {
        this.index = index;
        return this;
    }
    
    /**
     * Tigris project name.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("project")
    public String project;
    public CreateByIdRequest withProject(String project) {
        this.project = project;
        return this;
    }
    

    public CreateByIdRequest(){}
}
