/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.tigrisdata.tigris_core.models.shared;



/**
 * Data - Object containing the collection document.
 */

public class Data {
    public Data(){}
}
