/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.tigrisdata.tigris_core.models.shared;



/**
 * DescribeCollectionResponseSchema - Schema of this collection.
 */

public class DescribeCollectionResponseSchema {
    public DescribeCollectionResponseSchema(){}
}
