/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.tigrisdata.tigris_core.models.shared;



/**
 * Fields - To read specific fields from a document. Default is all.
 */

public class Fields {
    public Fields(){}
}
