/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.tigrisdata.tigris_core.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * GetResponse - OK
 */
public class GetResponse {
    /**
     * expiration ms
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("expires_in_ms")
    public Long expiresInMs;
    public GetResponse withExpiresInMs(Long expiresInMs) {
        this.expiresInMs = expiresInMs;
        return this;
    }
    
    /**
     * value
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("value")
    public String value;
    public GetResponse withValue(String value) {
        this.value = value;
        return this;
    }
    
    public GetResponse(){}
}
