/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.tigrisdata.tigris_core.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * GetSetResponse - OK
 */
public class GetSetResponse {
    /**
     * A detailed response message.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("message")
    public String message;
    public GetSetResponse withMessage(String message) {
        this.message = message;
        return this;
    }
    
    /**
     * An old value if exists
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("old_value")
    public String oldValue;
    public GetSetResponse withOldValue(String oldValue) {
        this.oldValue = oldValue;
        return this;
    }
    
    /**
     * An enum with value set as "set"
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("status")
    public String status;
    public GetSetResponse withStatus(String status) {
        this.status = status;
        return this;
    }
    
    public GetSetResponse(){}
}
