/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.tigrisdata.tigris_core.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;


public class InsertRequest {
    /**
     * Optionally specify a database branch name to perform operation on
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("branch")
    public String branch;

    public InsertRequest withBranch(String branch) {
        this.branch = branch;
        return this;
    }
    
    /**
     * Array of documents to insert. Each document is a JSON object.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("documents")
    public InsertRequestDocuments[] documents;

    public InsertRequest withDocuments(InsertRequestDocuments[] documents) {
        this.documents = documents;
        return this;
    }
    
    /**
     * additional options for insert requests.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("options")
    public InsertRequestOptions options;

    public InsertRequest withOptions(InsertRequestOptions options) {
        this.options = options;
        return this;
    }
    
    public InsertRequest(){}
}
