/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.tigrisdata.tigris_core.models.shared;



/**
 * ReadRequestFields - To read specific fields from a document. Default is all.
 */
public class ReadRequestFields {
    public ReadRequestFields(){}
}
