/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.tigrisdata.tigris_core.models.shared;



/**
 * Schema - Collections schema
 */

public class Schema {
    public Schema(){}
}
