/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.tigrisdata.tigris_core.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * StreamingReadResponse - OK
 */
public class StreamingReadResponse {
    /**
     * The Error type defines a logical error model
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("error")
    public Error error;
    public StreamingReadResponse withError(Error error) {
        this.error = error;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("result")
    public ReadResponse result;
    public StreamingReadResponse withResult(ReadResponse result) {
        this.result = result;
        return this;
    }
    

    public StreamingReadResponse(){}
}
