/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.tigrisdata.tigris_core.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * UpdateResponse - OK
 */
public class UpdateResponse {
    /**
     * Has metadata related to the documents stored.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("metadata")public ResponseMetadata metadata;
    public UpdateResponse withMetadata(ResponseMetadata metadata) {
        this.metadata = metadata;
        return this;
    }
    
    /**
     * Returns the number of documents modified.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("modified_count")public Integer modifiedCount;
    public UpdateResponse withModifiedCount(Integer modifiedCount) {
        this.modifiedCount = modifiedCount;
        return this;
    }
    
    /**
     * an enum with value set as "updated".
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("status")public String status;
    public UpdateResponse withStatus(String status) {
        this.status = status;
        return this;
    }
    
}
