/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.tigrisdata.tigris_core.models.operations;

import com.fasterxml.jackson.core.type.TypeReference;
import com.tigrisdata.tigris_core.models.errors.SDKError;
import com.tigrisdata.tigris_core.utils.LazySingletonValue;
import com.tigrisdata.tigris_core.utils.Utils;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.Optional;
import java.util.stream.Stream;
import org.openapitools.jackson.nullable.JsonNullable;


public class ManagementGetNamespaceMetadataRequestBuilder {

    private ManagementGetNamespaceMetadataRequest request;
    private final SDKMethodInterfaces.MethodCallManagementGetNamespaceMetadata sdk;

    public ManagementGetNamespaceMetadataRequestBuilder(SDKMethodInterfaces.MethodCallManagementGetNamespaceMetadata sdk) {
        this.sdk = sdk;
    }

    public ManagementGetNamespaceMetadataRequestBuilder request(ManagementGetNamespaceMetadataRequest request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public ManagementGetNamespaceMetadataResponse call() throws Exception {

        return sdk.getMetadata(
            request);
    }
}
