/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.tigrisdata.tigris_core.models.operations;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.core.type.TypeReference;
import com.tigrisdata.tigris_core.utils.SpeakeasyMetadata;
import com.tigrisdata.tigris_core.utils.Utils;
import java.io.InputStream;
import java.lang.Deprecated;
import java.math.BigDecimal;
import java.math.BigInteger;


public class ManagementGetNamespaceMetadataRequest {

    @SpeakeasyMetadata("request:mediaType=application/json")
    private com.tigrisdata.tigris_core.models.shared.GetNamespaceMetadataRequest getNamespaceMetadataRequest;

    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=metadataKey")
    private String metadataKey;

    public ManagementGetNamespaceMetadataRequest(
            com.tigrisdata.tigris_core.models.shared.GetNamespaceMetadataRequest getNamespaceMetadataRequest,
            String metadataKey) {
        Utils.checkNotNull(getNamespaceMetadataRequest, "getNamespaceMetadataRequest");
        Utils.checkNotNull(metadataKey, "metadataKey");
        this.getNamespaceMetadataRequest = getNamespaceMetadataRequest;
        this.metadataKey = metadataKey;
    }

    public com.tigrisdata.tigris_core.models.shared.GetNamespaceMetadataRequest getNamespaceMetadataRequest() {
        return getNamespaceMetadataRequest;
    }

    public String metadataKey() {
        return metadataKey;
    }

    public final static Builder builder() {
        return new Builder();
    }

    public ManagementGetNamespaceMetadataRequest withGetNamespaceMetadataRequest(com.tigrisdata.tigris_core.models.shared.GetNamespaceMetadataRequest getNamespaceMetadataRequest) {
        Utils.checkNotNull(getNamespaceMetadataRequest, "getNamespaceMetadataRequest");
        this.getNamespaceMetadataRequest = getNamespaceMetadataRequest;
        return this;
    }

    public ManagementGetNamespaceMetadataRequest withMetadataKey(String metadataKey) {
        Utils.checkNotNull(metadataKey, "metadataKey");
        this.metadataKey = metadataKey;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ManagementGetNamespaceMetadataRequest other = (ManagementGetNamespaceMetadataRequest) o;
        return 
            java.util.Objects.deepEquals(this.getNamespaceMetadataRequest, other.getNamespaceMetadataRequest) &&
            java.util.Objects.deepEquals(this.metadataKey, other.metadataKey);
    }
    
    @Override
    public int hashCode() {
        return java.util.Objects.hash(
            getNamespaceMetadataRequest,
            metadataKey);
    }
    
    @Override
    public String toString() {
        return Utils.toString(ManagementGetNamespaceMetadataRequest.class,
                "getNamespaceMetadataRequest", getNamespaceMetadataRequest,
                "metadataKey", metadataKey);
    }
    
    public final static class Builder {
 
        private com.tigrisdata.tigris_core.models.shared.GetNamespaceMetadataRequest getNamespaceMetadataRequest;
 
        private String metadataKey;  
        
        private Builder() {
          // force use of static builder() method
        }

        public Builder getNamespaceMetadataRequest(com.tigrisdata.tigris_core.models.shared.GetNamespaceMetadataRequest getNamespaceMetadataRequest) {
            Utils.checkNotNull(getNamespaceMetadataRequest, "getNamespaceMetadataRequest");
            this.getNamespaceMetadataRequest = getNamespaceMetadataRequest;
            return this;
        }

        public Builder metadataKey(String metadataKey) {
            Utils.checkNotNull(metadataKey, "metadataKey");
            this.metadataKey = metadataKey;
            return this;
        }
        
        public ManagementGetNamespaceMetadataRequest build() {
            return new ManagementGetNamespaceMetadataRequest(
                getNamespaceMetadataRequest,
                metadataKey);
        }
    }
}

