/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.tigrisdata.tigris_core.models.operations;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.core.type.TypeReference;
import com.tigrisdata.tigris_core.utils.SpeakeasyMetadata;
import com.tigrisdata.tigris_core.utils.Utils;
import java.io.InputStream;
import java.lang.Deprecated;
import java.math.BigDecimal;
import java.math.BigInteger;


public class RealtimeMessagesRequest {

    @SpeakeasyMetadata("request:mediaType=application/json")
    private com.tigrisdata.tigris_core.models.shared.MessagesRequest messagesRequest;

    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=channel")
    private String channel;

    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=project")
    private String project;

    public RealtimeMessagesRequest(
            com.tigrisdata.tigris_core.models.shared.MessagesRequest messagesRequest,
            String channel,
            String project) {
        Utils.checkNotNull(messagesRequest, "messagesRequest");
        Utils.checkNotNull(channel, "channel");
        Utils.checkNotNull(project, "project");
        this.messagesRequest = messagesRequest;
        this.channel = channel;
        this.project = project;
    }

    public com.tigrisdata.tigris_core.models.shared.MessagesRequest messagesRequest() {
        return messagesRequest;
    }

    public String channel() {
        return channel;
    }

    public String project() {
        return project;
    }

    public final static Builder builder() {
        return new Builder();
    }

    public RealtimeMessagesRequest withMessagesRequest(com.tigrisdata.tigris_core.models.shared.MessagesRequest messagesRequest) {
        Utils.checkNotNull(messagesRequest, "messagesRequest");
        this.messagesRequest = messagesRequest;
        return this;
    }

    public RealtimeMessagesRequest withChannel(String channel) {
        Utils.checkNotNull(channel, "channel");
        this.channel = channel;
        return this;
    }

    public RealtimeMessagesRequest withProject(String project) {
        Utils.checkNotNull(project, "project");
        this.project = project;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        RealtimeMessagesRequest other = (RealtimeMessagesRequest) o;
        return 
            java.util.Objects.deepEquals(this.messagesRequest, other.messagesRequest) &&
            java.util.Objects.deepEquals(this.channel, other.channel) &&
            java.util.Objects.deepEquals(this.project, other.project);
    }
    
    @Override
    public int hashCode() {
        return java.util.Objects.hash(
            messagesRequest,
            channel,
            project);
    }
    
    @Override
    public String toString() {
        return Utils.toString(RealtimeMessagesRequest.class,
                "messagesRequest", messagesRequest,
                "channel", channel,
                "project", project);
    }
    
    public final static class Builder {
 
        private com.tigrisdata.tigris_core.models.shared.MessagesRequest messagesRequest;
 
        private String channel;
 
        private String project;  
        
        private Builder() {
          // force use of static builder() method
        }

        public Builder messagesRequest(com.tigrisdata.tigris_core.models.shared.MessagesRequest messagesRequest) {
            Utils.checkNotNull(messagesRequest, "messagesRequest");
            this.messagesRequest = messagesRequest;
            return this;
        }

        public Builder channel(String channel) {
            Utils.checkNotNull(channel, "channel");
            this.channel = channel;
            return this;
        }

        public Builder project(String project) {
            Utils.checkNotNull(project, "project");
            this.project = project;
            return this;
        }
        
        public RealtimeMessagesRequest build() {
            return new RealtimeMessagesRequest(
                messagesRequest,
                channel,
                project);
        }
    }
}

