/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.tigrisdata.tigris_core.models.operations;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.Optional;
import org.openapitools.jackson.nullable.JsonNullable;


public class SDKMethodInterfaces {

    public interface MethodCallAuthGetAccessToken {
        com.tigrisdata.tigris_core.models.operations.AuthGetAccessTokenResponse getDirect() throws Exception;
    }


    public interface MethodCallHealthAPIHealth {
        com.tigrisdata.tigris_core.models.operations.HealthAPIHealthResponse getHealthDirect() throws Exception;
    }


    public interface MethodCallObservabilityGetInfo {
        com.tigrisdata.tigris_core.models.operations.ObservabilityGetInfoResponse getServerInfoDirect() throws Exception;
    }


    public interface MethodCallObservabilityQuotaUsage {
        com.tigrisdata.tigris_core.models.operations.ObservabilityQuotaUsageResponse observabilityQuotaUsage(
            com.tigrisdata.tigris_core.models.shared.QuotaUsageRequest request) throws Exception;
    }


    public interface MethodCallObservabilityQuotaLimits {
        com.tigrisdata.tigris_core.models.operations.ObservabilityQuotaLimitsResponse queryQuotaLimits(
            com.tigrisdata.tigris_core.models.shared.QuotaLimitsRequest request) throws Exception;
    }


    public interface MethodCallObservabilityQueryTimeSeriesMetrics {
        com.tigrisdata.tigris_core.models.operations.ObservabilityQueryTimeSeriesMetricsResponse queryTimeSeriesMetrics(
            com.tigrisdata.tigris_core.models.shared.QueryTimeSeriesMetricsRequest request) throws Exception;
    }


    public interface MethodCallCreateNamespace {
        com.tigrisdata.tigris_core.models.operations.CreateNamespaceResponse create(
            com.tigrisdata.tigris_core.models.shared.CreateNamespaceRequest request) throws Exception;
    }


    public interface MethodCallManagementDescribeNamespaces {
        com.tigrisdata.tigris_core.models.operations.ManagementDescribeNamespacesResponse getDirect() throws Exception;
    }


    public interface MethodCallManagementGetNamespaceMetadata {
        com.tigrisdata.tigris_core.models.operations.ManagementGetNamespaceMetadataResponse getMetadata(
            com.tigrisdata.tigris_core.models.operations.ManagementGetNamespaceMetadataRequest request) throws Exception;
    }


    public interface MethodCallManagementInsertNamespaceMetadata {
        com.tigrisdata.tigris_core.models.operations.ManagementInsertNamespaceMetadataResponse insertMetadata(
            com.tigrisdata.tigris_core.models.operations.ManagementInsertNamespaceMetadataRequest request) throws Exception;
    }


    public interface MethodCallManagementListNamespaces {
        com.tigrisdata.tigris_core.models.operations.ManagementListNamespacesResponse listDirect() throws Exception;
    }


    public interface MethodCallManagementUpdateNamespaceMetadata {
        com.tigrisdata.tigris_core.models.operations.ManagementUpdateNamespaceMetadataResponse updateMetadata(
            com.tigrisdata.tigris_core.models.operations.ManagementUpdateNamespaceMetadataRequest request) throws Exception;
    }


    public interface MethodCallManagementGetUserMetadata {
        com.tigrisdata.tigris_core.models.operations.ManagementGetUserMetadataResponse getMetadata(
            com.tigrisdata.tigris_core.models.operations.ManagementGetUserMetadataRequest request) throws Exception;
    }


    public interface MethodCallManagementInsertUserMetadata {
        com.tigrisdata.tigris_core.models.operations.ManagementInsertUserMetadataResponse insertMetadata(
            com.tigrisdata.tigris_core.models.operations.ManagementInsertUserMetadataRequest request) throws Exception;
    }


    public interface MethodCallManagementUpdateUserMetadata {
        com.tigrisdata.tigris_core.models.operations.ManagementUpdateUserMetadataResponse updateMetadata(
            com.tigrisdata.tigris_core.models.operations.ManagementUpdateUserMetadataRequest request) throws Exception;
    }


    public interface MethodCallTigrisCreateProject {
        com.tigrisdata.tigris_core.models.operations.TigrisCreateProjectResponse create(
            com.tigrisdata.tigris_core.models.operations.TigrisCreateProjectRequest request) throws Exception;
    }


    public interface MethodCallTigrisDeleteProject {
        com.tigrisdata.tigris_core.models.operations.TigrisDeleteProjectResponse deleteProject(
            com.tigrisdata.tigris_core.models.operations.TigrisDeleteProjectRequest request) throws Exception;
    }


    public interface MethodCallTigrisListProjects {
        com.tigrisdata.tigris_core.models.operations.TigrisListProjectsResponse listDirect() throws Exception;
    }


    public interface MethodCallTigrisDeleteAppKey {
        com.tigrisdata.tigris_core.models.operations.TigrisDeleteAppKeyResponse delete(
            com.tigrisdata.tigris_core.models.operations.TigrisDeleteAppKeyRequest request) throws Exception;
    }


    public interface MethodCallTigrisListAppKeys {
        com.tigrisdata.tigris_core.models.operations.TigrisListAppKeysResponse list(
            com.tigrisdata.tigris_core.models.operations.TigrisListAppKeysRequest request) throws Exception;
    }


    public interface MethodCallTigrisRotateAppKeySecret {
        com.tigrisdata.tigris_core.models.operations.TigrisRotateAppKeySecretResponse rotate(
            com.tigrisdata.tigris_core.models.operations.TigrisRotateAppKeySecretRequest request) throws Exception;
    }


    public interface MethodCallTigrisCreateAppKey {
        com.tigrisdata.tigris_core.models.operations.TigrisCreateAppKeyResponse tigrisCreateAppKey(
            com.tigrisdata.tigris_core.models.operations.TigrisCreateAppKeyRequest request) throws Exception;
    }


    public interface MethodCallTigrisUpdateAppKey {
        com.tigrisdata.tigris_core.models.operations.TigrisUpdateAppKeyResponse update(
            com.tigrisdata.tigris_core.models.operations.TigrisUpdateAppKeyRequest request) throws Exception;
    }


    public interface MethodCallCacheCreateCache {
        com.tigrisdata.tigris_core.models.operations.CacheCreateCacheResponse create(
            com.tigrisdata.tigris_core.models.operations.CacheCreateCacheRequest request) throws Exception;
    }


    public interface MethodCallCacheDeleteCache {
        com.tigrisdata.tigris_core.models.operations.CacheDeleteCacheResponse delete(
            com.tigrisdata.tigris_core.models.operations.CacheDeleteCacheRequest request) throws Exception;
    }


    public interface MethodCallCacheDel {
        com.tigrisdata.tigris_core.models.operations.CacheDelResponse deleteKeys(
            com.tigrisdata.tigris_core.models.operations.CacheDelRequest request) throws Exception;
    }


    public interface MethodCallCacheGet {
        com.tigrisdata.tigris_core.models.operations.CacheGetResponse getKey(
            com.tigrisdata.tigris_core.models.operations.CacheGetRequest request) throws Exception;
    }


    public interface MethodCallCacheGetSet {
        com.tigrisdata.tigris_core.models.operations.CacheGetSetResponse getSetKey(
            com.tigrisdata.tigris_core.models.operations.CacheGetSetRequest request) throws Exception;
    }


    public interface MethodCallCacheListCaches {
        com.tigrisdata.tigris_core.models.operations.CacheListCachesResponse list(
            com.tigrisdata.tigris_core.models.operations.CacheListCachesRequest request) throws Exception;
    }


    public interface MethodCallCacheKeys {
        com.tigrisdata.tigris_core.models.operations.CacheKeysResponse listKeys(
            com.tigrisdata.tigris_core.models.operations.CacheKeysRequest request) throws Exception;
    }


    public interface MethodCallCacheSet {
        com.tigrisdata.tigris_core.models.operations.CacheSetResponse setKey(
            com.tigrisdata.tigris_core.models.operations.CacheSetRequest request) throws Exception;
    }


    public interface MethodCallTigrisBeginTransaction {
        com.tigrisdata.tigris_core.models.operations.TigrisBeginTransactionResponse beginTransaction(
            com.tigrisdata.tigris_core.models.operations.TigrisBeginTransactionRequest request) throws Exception;
    }


    public interface MethodCallTigrisCommitTransaction {
        com.tigrisdata.tigris_core.models.operations.TigrisCommitTransactionResponse commitTransaction(
            com.tigrisdata.tigris_core.models.operations.TigrisCommitTransactionRequest request) throws Exception;
    }


    public interface MethodCallTigrisCreateBranch {
        com.tigrisdata.tigris_core.models.operations.TigrisCreateBranchResponse createBranch(
            com.tigrisdata.tigris_core.models.operations.TigrisCreateBranchRequest request) throws Exception;
    }


    public interface MethodCallTigrisDeleteBranch {
        com.tigrisdata.tigris_core.models.operations.TigrisDeleteBranchResponse deleteBranch(
            com.tigrisdata.tigris_core.models.operations.TigrisDeleteBranchRequest request) throws Exception;
    }


    public interface MethodCallTigrisDescribeDatabase {
        com.tigrisdata.tigris_core.models.operations.TigrisDescribeDatabaseResponse describe(
            com.tigrisdata.tigris_core.models.operations.TigrisDescribeDatabaseRequest request) throws Exception;
    }


    public interface MethodCallTigrisListCollections {
        com.tigrisdata.tigris_core.models.operations.TigrisListCollectionsResponse listCollections(
            com.tigrisdata.tigris_core.models.operations.TigrisListCollectionsRequest request) throws Exception;
    }


    public interface MethodCallTigrisRollbackTransaction {
        com.tigrisdata.tigris_core.models.operations.TigrisRollbackTransactionResponse rollbackTransaction(
            com.tigrisdata.tigris_core.models.operations.TigrisRollbackTransactionRequest request) throws Exception;
    }


    public interface MethodCallTigrisListBranches {
        com.tigrisdata.tigris_core.models.operations.TigrisListBranchesResponse tigrisListBranches(
            com.tigrisdata.tigris_core.models.operations.TigrisListBranchesRequest request) throws Exception;
    }


    public interface MethodCallTigrisCreateOrUpdateCollection {
        com.tigrisdata.tigris_core.models.operations.TigrisCreateOrUpdateCollectionResponse create(
            com.tigrisdata.tigris_core.models.operations.TigrisCreateOrUpdateCollectionRequest request) throws Exception;
    }


    public interface MethodCallTigrisDelete {
        com.tigrisdata.tigris_core.models.operations.TigrisDeleteResponse deleteDocuments(
            com.tigrisdata.tigris_core.models.operations.TigrisDeleteRequest request) throws Exception;
    }


    public interface MethodCallTigrisDescribeCollection {
        com.tigrisdata.tigris_core.models.operations.TigrisDescribeCollectionResponse describe(
            com.tigrisdata.tigris_core.models.operations.TigrisDescribeCollectionRequest request) throws Exception;
    }


    public interface MethodCallTigrisDropCollection {
        com.tigrisdata.tigris_core.models.operations.TigrisDropCollectionResponse drop(
            com.tigrisdata.tigris_core.models.operations.TigrisDropCollectionRequest request) throws Exception;
    }


    public interface MethodCallTigrisImport {
        com.tigrisdata.tigris_core.models.operations.TigrisImportResponse importDocuments(
            com.tigrisdata.tigris_core.models.operations.TigrisImportRequest request) throws Exception;
    }


    public interface MethodCallTigrisInsert {
        com.tigrisdata.tigris_core.models.operations.TigrisInsertResponse insertDocuments(
            com.tigrisdata.tigris_core.models.operations.TigrisInsertRequest request) throws Exception;
    }


    public interface MethodCallTigrisRead {
        com.tigrisdata.tigris_core.models.operations.TigrisReadResponse readDocuments(
            com.tigrisdata.tigris_core.models.operations.TigrisReadRequest request) throws Exception;
    }


    public interface MethodCallTigrisReplace {
        com.tigrisdata.tigris_core.models.operations.TigrisReplaceResponse replaceDocuments(
            com.tigrisdata.tigris_core.models.operations.TigrisReplaceRequest request) throws Exception;
    }


    public interface MethodCallTigrisSearch {
        com.tigrisdata.tigris_core.models.operations.TigrisSearchResponse searchDocuments(
            com.tigrisdata.tigris_core.models.operations.TigrisSearchRequest request) throws Exception;
    }


    public interface MethodCallTigrisUpdate {
        com.tigrisdata.tigris_core.models.operations.TigrisUpdateResponse updateDocuments(
            com.tigrisdata.tigris_core.models.operations.TigrisUpdateRequest request) throws Exception;
    }


    public interface MethodCallRealtimeGetRTChannel {
        com.tigrisdata.tigris_core.models.operations.RealtimeGetRTChannelResponse get(
            com.tigrisdata.tigris_core.models.operations.RealtimeGetRTChannelRequest request) throws Exception;
    }


    public interface MethodCallRealtimeReadMessages {
        com.tigrisdata.tigris_core.models.operations.RealtimeReadMessagesResponse getMessages(
            com.tigrisdata.tigris_core.models.operations.RealtimeReadMessagesRequest request) throws Exception;
    }


    public interface MethodCallRealtimeGetRTChannels {
        com.tigrisdata.tigris_core.models.operations.RealtimeGetRTChannelsResponse list(
            com.tigrisdata.tigris_core.models.operations.RealtimeGetRTChannelsRequest request) throws Exception;
    }


    public interface MethodCallRealtimeListSubscriptions {
        com.tigrisdata.tigris_core.models.operations.RealtimeListSubscriptionsResponse listSubscriptions(
            com.tigrisdata.tigris_core.models.operations.RealtimeListSubscriptionsRequest request) throws Exception;
    }


    public interface MethodCallRealtimeMessages {
        com.tigrisdata.tigris_core.models.operations.RealtimeMessagesResponse pushMessages(
            com.tigrisdata.tigris_core.models.operations.RealtimeMessagesRequest request) throws Exception;
    }


    public interface MethodCallRealtimePresence {
        com.tigrisdata.tigris_core.models.operations.RealtimePresenceResponse realtimePresence(
            com.tigrisdata.tigris_core.models.operations.RealtimePresenceRequest request) throws Exception;
    }


    public interface MethodCallSearchCreateById {
        com.tigrisdata.tigris_core.models.operations.SearchCreateByIdResponse createDocument(
            com.tigrisdata.tigris_core.models.operations.SearchCreateByIdRequest request) throws Exception;
    }


    public interface MethodCallSearchCreate {
        com.tigrisdata.tigris_core.models.operations.SearchCreateResponse createDocuments(
            com.tigrisdata.tigris_core.models.operations.SearchCreateRequest request) throws Exception;
    }


    public interface MethodCallSearchDelete {
        com.tigrisdata.tigris_core.models.operations.SearchDeleteResponse deleteDocuments(
            com.tigrisdata.tigris_core.models.operations.SearchDeleteRequest request) throws Exception;
    }


    public interface MethodCallSearchDeleteIndex {
        com.tigrisdata.tigris_core.models.operations.SearchDeleteIndexResponse deleteIndex(
            com.tigrisdata.tigris_core.models.operations.SearchDeleteIndexRequest request) throws Exception;
    }


    public interface MethodCallSearchSearch {
        com.tigrisdata.tigris_core.models.operations.SearchSearchResponse findDocuments(
            com.tigrisdata.tigris_core.models.operations.SearchSearchRequest request) throws Exception;
    }


    public interface MethodCallSearchGet {
        com.tigrisdata.tigris_core.models.operations.SearchGetResponse getDocuments(
            com.tigrisdata.tigris_core.models.operations.SearchGetRequest request) throws Exception;
    }


    public interface MethodCallSearchGetIndex {
        com.tigrisdata.tigris_core.models.operations.SearchGetIndexResponse getIndex(
            com.tigrisdata.tigris_core.models.operations.SearchGetIndexRequest request) throws Exception;
    }


    public interface MethodCallSearchListIndexes {
        com.tigrisdata.tigris_core.models.operations.SearchListIndexesResponse listIndexes(
            com.tigrisdata.tigris_core.models.operations.SearchListIndexesRequest request) throws Exception;
    }


    public interface MethodCallSearchDeleteByQuery {
        com.tigrisdata.tigris_core.models.operations.SearchDeleteByQueryResponse queryDeleteDocuments(
            com.tigrisdata.tigris_core.models.operations.SearchDeleteByQueryRequest request) throws Exception;
    }


    public interface MethodCallSearchCreateOrReplace {
        com.tigrisdata.tigris_core.models.operations.SearchCreateOrReplaceResponse replaceDocuments(
            com.tigrisdata.tigris_core.models.operations.SearchCreateOrReplaceRequest request) throws Exception;
    }


    public interface MethodCallSearchUpdate {
        com.tigrisdata.tigris_core.models.operations.SearchUpdateResponse updateDocuments(
            com.tigrisdata.tigris_core.models.operations.SearchUpdateRequest request) throws Exception;
    }


    public interface MethodCallSearchCreateOrUpdateIndex {
        com.tigrisdata.tigris_core.models.operations.SearchCreateOrUpdateIndexResponse updateIndex(
            com.tigrisdata.tigris_core.models.operations.SearchCreateOrUpdateIndexRequest request) throws Exception;
    }

}
