/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.tigrisdata.tigris_core.models.operations;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.core.type.TypeReference;
import com.tigrisdata.tigris_core.utils.SpeakeasyMetadata;
import com.tigrisdata.tigris_core.utils.Utils;
import java.io.InputStream;
import java.lang.Deprecated;
import java.math.BigDecimal;
import java.math.BigInteger;


public class TigrisDropCollectionRequest {

    @SpeakeasyMetadata("request:mediaType=application/json")
    private com.tigrisdata.tigris_core.models.shared.DropCollectionRequest dropCollectionRequest;

    /**
     * Collection name to delete.
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=collection")
    private String collection;

    /**
     * Project name whose db is under target to delete collection.
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=project")
    private String project;

    public TigrisDropCollectionRequest(
            com.tigrisdata.tigris_core.models.shared.DropCollectionRequest dropCollectionRequest,
            String collection,
            String project) {
        Utils.checkNotNull(dropCollectionRequest, "dropCollectionRequest");
        Utils.checkNotNull(collection, "collection");
        Utils.checkNotNull(project, "project");
        this.dropCollectionRequest = dropCollectionRequest;
        this.collection = collection;
        this.project = project;
    }

    public com.tigrisdata.tigris_core.models.shared.DropCollectionRequest dropCollectionRequest() {
        return dropCollectionRequest;
    }

    /**
     * Collection name to delete.
     */
    public String collection() {
        return collection;
    }

    /**
     * Project name whose db is under target to delete collection.
     */
    public String project() {
        return project;
    }

    public final static Builder builder() {
        return new Builder();
    }

    public TigrisDropCollectionRequest withDropCollectionRequest(com.tigrisdata.tigris_core.models.shared.DropCollectionRequest dropCollectionRequest) {
        Utils.checkNotNull(dropCollectionRequest, "dropCollectionRequest");
        this.dropCollectionRequest = dropCollectionRequest;
        return this;
    }

    /**
     * Collection name to delete.
     */
    public TigrisDropCollectionRequest withCollection(String collection) {
        Utils.checkNotNull(collection, "collection");
        this.collection = collection;
        return this;
    }

    /**
     * Project name whose db is under target to delete collection.
     */
    public TigrisDropCollectionRequest withProject(String project) {
        Utils.checkNotNull(project, "project");
        this.project = project;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        TigrisDropCollectionRequest other = (TigrisDropCollectionRequest) o;
        return 
            java.util.Objects.deepEquals(this.dropCollectionRequest, other.dropCollectionRequest) &&
            java.util.Objects.deepEquals(this.collection, other.collection) &&
            java.util.Objects.deepEquals(this.project, other.project);
    }
    
    @Override
    public int hashCode() {
        return java.util.Objects.hash(
            dropCollectionRequest,
            collection,
            project);
    }
    
    @Override
    public String toString() {
        return Utils.toString(TigrisDropCollectionRequest.class,
                "dropCollectionRequest", dropCollectionRequest,
                "collection", collection,
                "project", project);
    }
    
    public final static class Builder {
 
        private com.tigrisdata.tigris_core.models.shared.DropCollectionRequest dropCollectionRequest;
 
        private String collection;
 
        private String project;  
        
        private Builder() {
          // force use of static builder() method
        }

        public Builder dropCollectionRequest(com.tigrisdata.tigris_core.models.shared.DropCollectionRequest dropCollectionRequest) {
            Utils.checkNotNull(dropCollectionRequest, "dropCollectionRequest");
            this.dropCollectionRequest = dropCollectionRequest;
            return this;
        }

        /**
         * Collection name to delete.
         */
        public Builder collection(String collection) {
            Utils.checkNotNull(collection, "collection");
            this.collection = collection;
            return this;
        }

        /**
         * Project name whose db is under target to delete collection.
         */
        public Builder project(String project) {
            Utils.checkNotNull(project, "project");
            this.project = project;
            return this;
        }
        
        public TigrisDropCollectionRequest build() {
            return new TigrisDropCollectionRequest(
                dropCollectionRequest,
                collection,
                project);
        }
    }
}

