/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.tigrisdata.tigris_core.models.operations;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.core.type.TypeReference;
import com.tigrisdata.tigris_core.utils.SpeakeasyMetadata;
import com.tigrisdata.tigris_core.utils.Utils;
import java.io.InputStream;
import java.lang.Deprecated;
import java.math.BigDecimal;
import java.math.BigInteger;


public class TigrisReadRequest {

    @SpeakeasyMetadata("request:mediaType=application/json")
    private com.tigrisdata.tigris_core.models.shared.ReadRequest readRequest;

    /**
     * Collection name to read documents from.
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=collection")
    private String collection;

    /**
     * Project name whose db is under target to read documents from.
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=project")
    private String project;

    public TigrisReadRequest(
            com.tigrisdata.tigris_core.models.shared.ReadRequest readRequest,
            String collection,
            String project) {
        Utils.checkNotNull(readRequest, "readRequest");
        Utils.checkNotNull(collection, "collection");
        Utils.checkNotNull(project, "project");
        this.readRequest = readRequest;
        this.collection = collection;
        this.project = project;
    }

    public com.tigrisdata.tigris_core.models.shared.ReadRequest readRequest() {
        return readRequest;
    }

    /**
     * Collection name to read documents from.
     */
    public String collection() {
        return collection;
    }

    /**
     * Project name whose db is under target to read documents from.
     */
    public String project() {
        return project;
    }

    public final static Builder builder() {
        return new Builder();
    }

    public TigrisReadRequest withReadRequest(com.tigrisdata.tigris_core.models.shared.ReadRequest readRequest) {
        Utils.checkNotNull(readRequest, "readRequest");
        this.readRequest = readRequest;
        return this;
    }

    /**
     * Collection name to read documents from.
     */
    public TigrisReadRequest withCollection(String collection) {
        Utils.checkNotNull(collection, "collection");
        this.collection = collection;
        return this;
    }

    /**
     * Project name whose db is under target to read documents from.
     */
    public TigrisReadRequest withProject(String project) {
        Utils.checkNotNull(project, "project");
        this.project = project;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        TigrisReadRequest other = (TigrisReadRequest) o;
        return 
            java.util.Objects.deepEquals(this.readRequest, other.readRequest) &&
            java.util.Objects.deepEquals(this.collection, other.collection) &&
            java.util.Objects.deepEquals(this.project, other.project);
    }
    
    @Override
    public int hashCode() {
        return java.util.Objects.hash(
            readRequest,
            collection,
            project);
    }
    
    @Override
    public String toString() {
        return Utils.toString(TigrisReadRequest.class,
                "readRequest", readRequest,
                "collection", collection,
                "project", project);
    }
    
    public final static class Builder {
 
        private com.tigrisdata.tigris_core.models.shared.ReadRequest readRequest;
 
        private String collection;
 
        private String project;  
        
        private Builder() {
          // force use of static builder() method
        }

        public Builder readRequest(com.tigrisdata.tigris_core.models.shared.ReadRequest readRequest) {
            Utils.checkNotNull(readRequest, "readRequest");
            this.readRequest = readRequest;
            return this;
        }

        /**
         * Collection name to read documents from.
         */
        public Builder collection(String collection) {
            Utils.checkNotNull(collection, "collection");
            this.collection = collection;
            return this;
        }

        /**
         * Project name whose db is under target to read documents from.
         */
        public Builder project(String project) {
            Utils.checkNotNull(project, "project");
            this.project = project;
            return this;
        }
        
        public TigrisReadRequest build() {
            return new TigrisReadRequest(
                readRequest,
                collection,
                project);
        }
    }
}

