/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.tigrisdata.tigris_core.models.shared;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.core.type.TypeReference;
import com.tigrisdata.tigris_core.utils.Utils;
import java.io.InputStream;
import java.lang.Deprecated;
import java.math.BigDecimal;
import java.math.BigInteger;

public enum Aggregator {
    ROLLUP_AGGREGATOR_SUM("ROLLUP_AGGREGATOR_SUM"),
    ROLLUP_AGGREGATOR_COUNT("ROLLUP_AGGREGATOR_COUNT"),
    ROLLUP_AGGREGATOR_MIN("ROLLUP_AGGREGATOR_MIN"),
    ROLLUP_AGGREGATOR_MAX("ROLLUP_AGGREGATOR_MAX"),
    ROLLUP_AGGREGATOR_AVG("ROLLUP_AGGREGATOR_AVG");

    @JsonValue
    private final String value;

    private Aggregator(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
}
