/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.tigrisdata.tigris_core.models.shared;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.type.TypeReference;
import com.tigrisdata.tigris_core.utils.Utils;
import java.io.InputStream;
import java.lang.Deprecated;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.Optional;

/**
 * BeginTransactionRequest - Start new transaction in project specified by "project".
 */

public class BeginTransactionRequest {

    /**
     * Optionally specify a project branch name to perform operation on
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("branch")
    private Optional<? extends String> branch;

    /**
     * Options that can be used to modify the transaction semantics.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("options")
    private Optional<? extends TransactionOptions> options;

    public BeginTransactionRequest(
            @JsonProperty("branch") Optional<? extends String> branch,
            @JsonProperty("options") Optional<? extends TransactionOptions> options) {
        Utils.checkNotNull(branch, "branch");
        Utils.checkNotNull(options, "options");
        this.branch = branch;
        this.options = options;
    }

    /**
     * Optionally specify a project branch name to perform operation on
     */
    public Optional<? extends String> branch() {
        return branch;
    }

    /**
     * Options that can be used to modify the transaction semantics.
     */
    public Optional<? extends TransactionOptions> options() {
        return options;
    }

    public final static Builder builder() {
        return new Builder();
    }

    /**
     * Optionally specify a project branch name to perform operation on
     */
    public BeginTransactionRequest withBranch(String branch) {
        Utils.checkNotNull(branch, "branch");
        this.branch = Optional.ofNullable(branch);
        return this;
    }

    /**
     * Optionally specify a project branch name to perform operation on
     */
    public BeginTransactionRequest withBranch(Optional<? extends String> branch) {
        Utils.checkNotNull(branch, "branch");
        this.branch = branch;
        return this;
    }

    /**
     * Options that can be used to modify the transaction semantics.
     */
    public BeginTransactionRequest withOptions(TransactionOptions options) {
        Utils.checkNotNull(options, "options");
        this.options = Optional.ofNullable(options);
        return this;
    }

    /**
     * Options that can be used to modify the transaction semantics.
     */
    public BeginTransactionRequest withOptions(Optional<? extends TransactionOptions> options) {
        Utils.checkNotNull(options, "options");
        this.options = options;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        BeginTransactionRequest other = (BeginTransactionRequest) o;
        return 
            java.util.Objects.deepEquals(this.branch, other.branch) &&
            java.util.Objects.deepEquals(this.options, other.options);
    }
    
    @Override
    public int hashCode() {
        return java.util.Objects.hash(
            branch,
            options);
    }
    
    @Override
    public String toString() {
        return Utils.toString(BeginTransactionRequest.class,
                "branch", branch,
                "options", options);
    }
    
    public final static class Builder {
 
        private Optional<? extends String> branch = Optional.empty();
 
        private Optional<? extends TransactionOptions> options = Optional.empty();  
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * Optionally specify a project branch name to perform operation on
         */
        public Builder branch(String branch) {
            Utils.checkNotNull(branch, "branch");
            this.branch = Optional.ofNullable(branch);
            return this;
        }

        /**
         * Optionally specify a project branch name to perform operation on
         */
        public Builder branch(Optional<? extends String> branch) {
            Utils.checkNotNull(branch, "branch");
            this.branch = branch;
            return this;
        }

        /**
         * Options that can be used to modify the transaction semantics.
         */
        public Builder options(TransactionOptions options) {
            Utils.checkNotNull(options, "options");
            this.options = Optional.ofNullable(options);
            return this;
        }

        /**
         * Options that can be used to modify the transaction semantics.
         */
        public Builder options(Optional<? extends TransactionOptions> options) {
            Utils.checkNotNull(options, "options");
            this.options = options;
            return this;
        }
        
        public BeginTransactionRequest build() {
            return new BeginTransactionRequest(
                branch,
                options);
        }
    }
}

