/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.tigrisdata.tigris_core.models.shared;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.type.TypeReference;
import com.tigrisdata.tigris_core.utils.Utils;
import java.io.InputStream;
import java.lang.Deprecated;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.Optional;


public class GetResponse {

    /**
     * expiration ms
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("expires_in_ms")
    private Optional<? extends Long> expiresInMs;

    /**
     * value
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("value")
    private Optional<? extends String> value;

    public GetResponse(
            @JsonProperty("expires_in_ms") Optional<? extends Long> expiresInMs,
            @JsonProperty("value") Optional<? extends String> value) {
        Utils.checkNotNull(expiresInMs, "expiresInMs");
        Utils.checkNotNull(value, "value");
        this.expiresInMs = expiresInMs;
        this.value = value;
    }

    /**
     * expiration ms
     */
    public Optional<? extends Long> expiresInMs() {
        return expiresInMs;
    }

    /**
     * value
     */
    public Optional<? extends String> value() {
        return value;
    }

    public final static Builder builder() {
        return new Builder();
    }

    /**
     * expiration ms
     */
    public GetResponse withExpiresInMs(long expiresInMs) {
        Utils.checkNotNull(expiresInMs, "expiresInMs");
        this.expiresInMs = Optional.ofNullable(expiresInMs);
        return this;
    }

    /**
     * expiration ms
     */
    public GetResponse withExpiresInMs(Optional<? extends Long> expiresInMs) {
        Utils.checkNotNull(expiresInMs, "expiresInMs");
        this.expiresInMs = expiresInMs;
        return this;
    }

    /**
     * value
     */
    public GetResponse withValue(String value) {
        Utils.checkNotNull(value, "value");
        this.value = Optional.ofNullable(value);
        return this;
    }

    /**
     * value
     */
    public GetResponse withValue(Optional<? extends String> value) {
        Utils.checkNotNull(value, "value");
        this.value = value;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetResponse other = (GetResponse) o;
        return 
            java.util.Objects.deepEquals(this.expiresInMs, other.expiresInMs) &&
            java.util.Objects.deepEquals(this.value, other.value);
    }
    
    @Override
    public int hashCode() {
        return java.util.Objects.hash(
            expiresInMs,
            value);
    }
    
    @Override
    public String toString() {
        return Utils.toString(GetResponse.class,
                "expiresInMs", expiresInMs,
                "value", value);
    }
    
    public final static class Builder {
 
        private Optional<? extends Long> expiresInMs = Optional.empty();
 
        private Optional<? extends String> value = Optional.empty();  
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * expiration ms
         */
        public Builder expiresInMs(long expiresInMs) {
            Utils.checkNotNull(expiresInMs, "expiresInMs");
            this.expiresInMs = Optional.ofNullable(expiresInMs);
            return this;
        }

        /**
         * expiration ms
         */
        public Builder expiresInMs(Optional<? extends Long> expiresInMs) {
            Utils.checkNotNull(expiresInMs, "expiresInMs");
            this.expiresInMs = expiresInMs;
            return this;
        }

        /**
         * value
         */
        public Builder value(String value) {
            Utils.checkNotNull(value, "value");
            this.value = Optional.ofNullable(value);
            return this;
        }

        /**
         * value
         */
        public Builder value(Optional<? extends String> value) {
            Utils.checkNotNull(value, "value");
            this.value = value;
            return this;
        }
        
        public GetResponse build() {
            return new GetResponse(
                expiresInMs,
                value);
        }
    }
}

