/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.tigrisdata.tigris_core.models.shared;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.type.TypeReference;
import com.tigrisdata.tigris_core.utils.Utils;
import java.io.InputStream;
import java.lang.Deprecated;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.Optional;


public class SearchHit {

    /**
     * Actual search document
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("data")
    private Optional<? extends SearchHitData> data;

    /**
     * Contains metadata related to the search hit, has information about document created_at/updated_at as well.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("metadata")
    private Optional<? extends SearchHitMeta> metadata;

    public SearchHit(
            @JsonProperty("data") Optional<? extends SearchHitData> data,
            @JsonProperty("metadata") Optional<? extends SearchHitMeta> metadata) {
        Utils.checkNotNull(data, "data");
        Utils.checkNotNull(metadata, "metadata");
        this.data = data;
        this.metadata = metadata;
    }

    /**
     * Actual search document
     */
    public Optional<? extends SearchHitData> data() {
        return data;
    }

    /**
     * Contains metadata related to the search hit, has information about document created_at/updated_at as well.
     */
    public Optional<? extends SearchHitMeta> metadata() {
        return metadata;
    }

    public final static Builder builder() {
        return new Builder();
    }

    /**
     * Actual search document
     */
    public SearchHit withData(SearchHitData data) {
        Utils.checkNotNull(data, "data");
        this.data = Optional.ofNullable(data);
        return this;
    }

    /**
     * Actual search document
     */
    public SearchHit withData(Optional<? extends SearchHitData> data) {
        Utils.checkNotNull(data, "data");
        this.data = data;
        return this;
    }

    /**
     * Contains metadata related to the search hit, has information about document created_at/updated_at as well.
     */
    public SearchHit withMetadata(SearchHitMeta metadata) {
        Utils.checkNotNull(metadata, "metadata");
        this.metadata = Optional.ofNullable(metadata);
        return this;
    }

    /**
     * Contains metadata related to the search hit, has information about document created_at/updated_at as well.
     */
    public SearchHit withMetadata(Optional<? extends SearchHitMeta> metadata) {
        Utils.checkNotNull(metadata, "metadata");
        this.metadata = metadata;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        SearchHit other = (SearchHit) o;
        return 
            java.util.Objects.deepEquals(this.data, other.data) &&
            java.util.Objects.deepEquals(this.metadata, other.metadata);
    }
    
    @Override
    public int hashCode() {
        return java.util.Objects.hash(
            data,
            metadata);
    }
    
    @Override
    public String toString() {
        return Utils.toString(SearchHit.class,
                "data", data,
                "metadata", metadata);
    }
    
    public final static class Builder {
 
        private Optional<? extends SearchHitData> data = Optional.empty();
 
        private Optional<? extends SearchHitMeta> metadata = Optional.empty();  
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * Actual search document
         */
        public Builder data(SearchHitData data) {
            Utils.checkNotNull(data, "data");
            this.data = Optional.ofNullable(data);
            return this;
        }

        /**
         * Actual search document
         */
        public Builder data(Optional<? extends SearchHitData> data) {
            Utils.checkNotNull(data, "data");
            this.data = data;
            return this;
        }

        /**
         * Contains metadata related to the search hit, has information about document created_at/updated_at as well.
         */
        public Builder metadata(SearchHitMeta metadata) {
            Utils.checkNotNull(metadata, "metadata");
            this.metadata = Optional.ofNullable(metadata);
            return this;
        }

        /**
         * Contains metadata related to the search hit, has information about document created_at/updated_at as well.
         */
        public Builder metadata(Optional<? extends SearchHitMeta> metadata) {
            Utils.checkNotNull(metadata, "metadata");
            this.metadata = metadata;
            return this;
        }
        
        public SearchHit build() {
            return new SearchHit(
                data,
                metadata);
        }
    }
}

