/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.tigrisdata.tigris_core.models.shared;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.type.TypeReference;
import com.tigrisdata.tigris_core.utils.Utils;
import java.io.InputStream;
import java.lang.Deprecated;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.Optional;

/**
 * UpdateRequestOptions - Additional options for update requests.
 */

public class UpdateRequestOptions {

    /**
     * A collation allows you to specify string comparison rules. Default is case-sensitive, to override it you can set this option to 'ci' that will apply to all the text fields in the filters.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("collation")
    private Optional<? extends Collation> collation;

    /**
     * Limit the number of documents to be updated
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("limit")
    private Optional<? extends Long> limit;

    /**
     * Additional options to modify write requests.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("write_options")
    private Optional<? extends WriteOptions> writeOptions;

    public UpdateRequestOptions(
            @JsonProperty("collation") Optional<? extends Collation> collation,
            @JsonProperty("limit") Optional<? extends Long> limit,
            @JsonProperty("write_options") Optional<? extends WriteOptions> writeOptions) {
        Utils.checkNotNull(collation, "collation");
        Utils.checkNotNull(limit, "limit");
        Utils.checkNotNull(writeOptions, "writeOptions");
        this.collation = collation;
        this.limit = limit;
        this.writeOptions = writeOptions;
    }

    /**
     * A collation allows you to specify string comparison rules. Default is case-sensitive, to override it you can set this option to 'ci' that will apply to all the text fields in the filters.
     */
    public Optional<? extends Collation> collation() {
        return collation;
    }

    /**
     * Limit the number of documents to be updated
     */
    public Optional<? extends Long> limit() {
        return limit;
    }

    /**
     * Additional options to modify write requests.
     */
    public Optional<? extends WriteOptions> writeOptions() {
        return writeOptions;
    }

    public final static Builder builder() {
        return new Builder();
    }

    /**
     * A collation allows you to specify string comparison rules. Default is case-sensitive, to override it you can set this option to 'ci' that will apply to all the text fields in the filters.
     */
    public UpdateRequestOptions withCollation(Collation collation) {
        Utils.checkNotNull(collation, "collation");
        this.collation = Optional.ofNullable(collation);
        return this;
    }

    /**
     * A collation allows you to specify string comparison rules. Default is case-sensitive, to override it you can set this option to 'ci' that will apply to all the text fields in the filters.
     */
    public UpdateRequestOptions withCollation(Optional<? extends Collation> collation) {
        Utils.checkNotNull(collation, "collation");
        this.collation = collation;
        return this;
    }

    /**
     * Limit the number of documents to be updated
     */
    public UpdateRequestOptions withLimit(long limit) {
        Utils.checkNotNull(limit, "limit");
        this.limit = Optional.ofNullable(limit);
        return this;
    }

    /**
     * Limit the number of documents to be updated
     */
    public UpdateRequestOptions withLimit(Optional<? extends Long> limit) {
        Utils.checkNotNull(limit, "limit");
        this.limit = limit;
        return this;
    }

    /**
     * Additional options to modify write requests.
     */
    public UpdateRequestOptions withWriteOptions(WriteOptions writeOptions) {
        Utils.checkNotNull(writeOptions, "writeOptions");
        this.writeOptions = Optional.ofNullable(writeOptions);
        return this;
    }

    /**
     * Additional options to modify write requests.
     */
    public UpdateRequestOptions withWriteOptions(Optional<? extends WriteOptions> writeOptions) {
        Utils.checkNotNull(writeOptions, "writeOptions");
        this.writeOptions = writeOptions;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        UpdateRequestOptions other = (UpdateRequestOptions) o;
        return 
            java.util.Objects.deepEquals(this.collation, other.collation) &&
            java.util.Objects.deepEquals(this.limit, other.limit) &&
            java.util.Objects.deepEquals(this.writeOptions, other.writeOptions);
    }
    
    @Override
    public int hashCode() {
        return java.util.Objects.hash(
            collation,
            limit,
            writeOptions);
    }
    
    @Override
    public String toString() {
        return Utils.toString(UpdateRequestOptions.class,
                "collation", collation,
                "limit", limit,
                "writeOptions", writeOptions);
    }
    
    public final static class Builder {
 
        private Optional<? extends Collation> collation = Optional.empty();
 
        private Optional<? extends Long> limit = Optional.empty();
 
        private Optional<? extends WriteOptions> writeOptions = Optional.empty();  
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * A collation allows you to specify string comparison rules. Default is case-sensitive, to override it you can set this option to 'ci' that will apply to all the text fields in the filters.
         */
        public Builder collation(Collation collation) {
            Utils.checkNotNull(collation, "collation");
            this.collation = Optional.ofNullable(collation);
            return this;
        }

        /**
         * A collation allows you to specify string comparison rules. Default is case-sensitive, to override it you can set this option to 'ci' that will apply to all the text fields in the filters.
         */
        public Builder collation(Optional<? extends Collation> collation) {
            Utils.checkNotNull(collation, "collation");
            this.collation = collation;
            return this;
        }

        /**
         * Limit the number of documents to be updated
         */
        public Builder limit(long limit) {
            Utils.checkNotNull(limit, "limit");
            this.limit = Optional.ofNullable(limit);
            return this;
        }

        /**
         * Limit the number of documents to be updated
         */
        public Builder limit(Optional<? extends Long> limit) {
            Utils.checkNotNull(limit, "limit");
            this.limit = limit;
            return this;
        }

        /**
         * Additional options to modify write requests.
         */
        public Builder writeOptions(WriteOptions writeOptions) {
            Utils.checkNotNull(writeOptions, "writeOptions");
            this.writeOptions = Optional.ofNullable(writeOptions);
            return this;
        }

        /**
         * Additional options to modify write requests.
         */
        public Builder writeOptions(Optional<? extends WriteOptions> writeOptions) {
            Utils.checkNotNull(writeOptions, "writeOptions");
            this.writeOptions = writeOptions;
            return this;
        }
        
        public UpdateRequestOptions build() {
            return new UpdateRequestOptions(
                collation,
                limit,
                writeOptions);
        }
    }
}

